### ISSUE TITLE
Dynamic dashboard is empty

### ISSUE THREAD

**Issue by andrewdebnar** [kabisaict/dashboard#7]
I've updated the .env and config/config.yml and the dashboard is blank. I've left the example Notification text in the config.yml and still nothing is displayed. 

I've tried http://localhost:3030/dynamic and http://localhost:3030
http://localhost:3030/dynamic - is a black page with nothing on it
http://localhost:3030 gives an error to many redirects.

What am I missing here?

**Comment by pascalw** [comment]
Hi @andrewdebnar I think you dashboard should be available under `/<name of your dashboard>`. E.g. with this config.yml:

```
dashboards:
  myboard:
    title: My Awesome Dashboard
    widget_width: 360
    widget_height: 170
    num_columns: 5
```

That should be available under `/myboard`. Please post your config.yml if that doesn't work.
